Добавлена графика
htmlacademy-htmlcss/1975777-sedona-33 pull request #4
Opened 2022-01-27 22:27 UTC by sipengo-dev

2022-01-28 10:51 UTC, what1s1ove reviewed
Нужно сделать красивые и понятные имена для всех картинок

2022-01-28 10:51 UTC, what1s1ove commented on catalog.html
> +                 <img class="product-card-image" src="images/hotel-1 (1).jpg" width="299" height="206" alt="Фото гостиницы">
плохое название для картинки. То, как оно экспортируется с фигмы, не должно управлять тем, как это должно выглядеть. Ты, как разработчик, должна сама решать, и делать красиво и удобно.

2022-01-29 09:24 UTC, what1s1ove requested changes
По коду все хорошо, но с названием картинок что-то не выходит. Оставил комментов. Нужно сделать название картинок более осмысленным

2022-01-29 09:24 UTC, what1s1ove commented on images/Ellipse 4.svg
> +<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
название картинок должно быть с маленькой буквы, и осмысленное

2022-01-29 09:24 UTC, what1s1ove commented on images/bread_crumbs2.svg
> +<svg width="5" height="8" viewBox="0 0 5 8" fill="none" xmlns="http://www.w3.org/2000/svg">
давай лучше разделять название картинок через `-`. Например `very-good-picture.png`

2022-01-29 09:24 UTC, what1s1ove commented on images/home 1.svg
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
В названиях картинок не должно быть пробелов

2022-01-29 09:24 UTC, what1s1ove commented on styles/styles.css
> +@font-face {
Так, пока стили подключать не нужно) Буду ревьюить их в некст разделе

2022-01-29 10:11 UTC, sipengo-dev commented on images/Ellipse 4.svg
> +<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
эту картинку я еще в проект не вставляла, поэтому не сделала название, ее буду прорисовывать css-ом

2022-01-29 10:11 UTC, sipengo-dev commented on images/bread_crumbs2.svg
> +<svg width="5" height="8" viewBox="0 0 5 8" fill="none" xmlns="http://www.w3.org/2000/svg">
окей попровлю)

2022-01-29 10:12 UTC, sipengo-dev commented on images/home 1.svg
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
поправлю)

2022-01-29 10:12 UTC, sipengo-dev commented on styles/styles.css
> +@font-face {
по стилям у меня есть вопросы, работа с фонам не удается

2022-01-29 10:13 UTC, sipengo-dev commented on styles/styles.css
> +@font-face {
где я могу их задать?

2022-01-29 10:16 UTC, what1s1ove commented on styles/styles.css
> +@font-face {
Давай сейчас полностью удали стили, и задашь в следующем задании. Это задание про графику. Не нужно все мешать.

2022-01-29 10:17 UTC, what1s1ove commented on images/Ellipse 4.svg
> +<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
сейчас нужно всем картинкам сделать нормальные названия

2022-01-29 10:42 UTC, sipengo-dev commented on styles/styles.css
> +@font-face {
хорошо, отключу.

2022-01-29 11:00 UTC, sipengo-dev commented on styles/styles.css
> +@font-face {
все переименовала

2022-01-29 11:00 UTC, sipengo-dev commented on styles/styles.css
> +@font-face {
делать новый PR?

2022-01-29 18:12 UTC, what1s1ove commented on styles/styles.css
> +@font-face {
Ни в коем случае) Отправляй на проверку ещё раз в интерфейсе курса

2022-01-29 20:39 UTC, sipengo-dev commented on styles/styles.css
> +@font-face {
отправила на проверку, но не поняла, что не делать "ни в коем случае")

2022-01-30 08:47 UTC, what1s1ove commented on styles/styles.css
> +@font-face {
в плане что не нужно создавать новый ПР после правок)
нужно доделывать старый, и отправлять ещё раз на проверку)

2022-01-30 08:47 UTC, merged