Базовая стилизация всех страниц
htmlacademy-htmlcss/1975777-sedona-33 pull request #5
Opened 2022-01-31 20:08 UTC by sipengo-dev

2022-02-01 04:44 UTC, what1s1ove requested changes
по стилям в целом оки, нужно поправить нужно чуть поправить их и разметку

2022-02-01 04:44 UTC, what1s1ove commented on catalog.html
> +    <div class="product-card">
в первую очередь это список. список карточек. нужно делать списком

2022-02-01 04:44 UTC, what1s1ove commented on catalog.html
> +    <select class="hotel-on-page-list" aria-label="Сортировка">
секция это отдельный блок, в котором всегда должен быть заголовок
Пагинация не может существовать без списка товаров, по этому они должны быть в одной секции

2022-02-01 04:44 UTC, what1s1ove commented on catalog.html
> +    <section class="foter-social">
в секциях должен быть заголовок

2022-02-01 04:44 UTC, what1s1ove commented on catalog.html
> +    <section>
в секциях должен быть заголовок. тут можно без секции

2022-02-01 04:44 UTC, what1s1ove commented on catalog.html
> +      <h2 class="footer-tel-title">+7 (812) 812-12-12</h2>
тут нужно сделать номер через ссылку. секция не нужна

2022-02-01 04:44 UTC, what1s1ove commented on index.html
> +      <a class="footer-phone-title" href="tel:+78128121212">+7 (812) 812-12-12</a>
сейчас футер и хедер немного разные на двух странах (по разметке). они должен быть одинаковы.

номер должен быть ссылкой, тут верно. такой же должен быть на каталоге

2022-02-01 04:44 UTC, what1s1ove commented on styles/styles.css
> +  font-family: "PT-Sants", sans-serif;
```suggestion
  font-family: "PT-Sants", "Aria", sans-serif;
```
должен быть ещё безопасный шрифт

2022-02-01 04:44 UTC, what1s1ove commented on styles/styles.css
> +.info-email-title {
```suggestion
}

.info-email-title {
```
По стайл гайду, между правилами должны быть пробелы

2022-02-01 17:15 UTC, sipengo-dev commented on catalog.html
> +    <section>
здесь ты пишешь, что секцию стоит удалить, а как я потом буду это компоновать во флексах или ссылки тоже в лежат боксах?

2022-02-01 18:54 UTC, sipengo-dev commented on catalog.html
> +    <div class="product-card">
всесто div -----> ul ?

2022-02-01 21:40 UTC, what1s1ove commented on catalog.html
> +    <section>
Можешь обернуть просто в `p`, если там нужно)

2022-02-02 08:08 UTC, what1s1ove commented on catalog.html
> +          <input class="infastructure-input" type="checkbox" name="pool" checked>Бассейн
лейбл должен быть свой для каждого инпута

2022-02-02 08:08 UTC, what1s1ove commented on catalog.html
> +          <img class="breadcrumbs-image" src="images/bread-crumbs.svg" width="5" height="8" alt="указатель">
мы уже знаем, что есть контентные картинки (тег `img`), а есть декоративные (что вставляются через css)
эта картинка не несет никакого контентного смысла, по этому её стоит делать в css

2022-02-02 08:08 UTC, what1s1ove commented on catalog.html
> +        <label class="type-home">
тут так же, для каждого инпута, должен быть свой лейбл

2022-02-02 08:08 UTC, what1s1ove commented on catalog.html
> +      <img class="mode-image" src="images/mode-tile.svg" width="16" height="14" alt="Плитка режима просмотра">
так же по поводу картинок - они декоративные

2022-02-02 08:08 UTC, what1s1ove commented on catalog.html
> +    <section class="foter-social">
заголовок так и не появился

2022-02-02 08:08 UTC, what1s1ove commented on catalog.html
> +            <img class="social-image" src="images/twitter.svg" width="18" height="15" alt="ссылка на Твиттер">
тоже лучше сделать декоратиными картинками

2022-02-02 08:08 UTC, merged